USE [master]
GO

/****** Object:  Database [SchrumChores]  ******/
CREATE DATABASE [SchrumChores] ON  PRIMARY 
( NAME = N'SchrumChores', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\SchrumChores.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SchrumChores_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\SchrumChores_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SchrumChores] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SchrumChores].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SchrumChores] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SchrumChores] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SchrumChores] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SchrumChores] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SchrumChores] SET ARITHABORT OFF 
GO

ALTER DATABASE [SchrumChores] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SchrumChores] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SchrumChores] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SchrumChores] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SchrumChores] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SchrumChores] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SchrumChores] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SchrumChores] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SchrumChores] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SchrumChores] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SchrumChores] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SchrumChores] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SchrumChores] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SchrumChores] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SchrumChores] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SchrumChores] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SchrumChores] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SchrumChores] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SchrumChores] SET  READ_WRITE 
GO

ALTER DATABASE [SchrumChores] SET RECOVERY FULL 
GO

ALTER DATABASE [SchrumChores] SET  MULTI_USER 
GO

ALTER DATABASE [SchrumChores] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SchrumChores] SET DB_CHAINING OFF 
GO


